export const BUY_ITEM = "BUY_ITEM"
export const CANCEL_ITEM = "CANCEL_ITEM"
export const MENU_REQUEST = "MENU_REQUEST"
export const MENU_SUCCESS = "MENU_SUCCESS"
export const MENU_FAILURE = "MENU_FAILURE"
export const MENUOUT = "MENUOUT"
